source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'7.0'
inhibit_all_warnings!
pod 'AFNetworking'
pod 'JSONModel'
pod 'BlocksKit'
pod 'RefreshControl'
pod 'JGProgressHUD'
pod 'TTTAttributedLabel'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MDRadialProgress'
pod 'Reachability'
