platform :ios,'7.0'
pod 'AFNetworking', '~> 2.3.1'
pod 'JSONModel'
pod 'BlocksKit'
pod 'RefreshControl', :head
pod 'UIActionSheet+Blocks'
pod 'UIAlertView+Blocks'
pod 'JGProgressHUD'
pod 'MessageBanner'
pod 'SSKeychain'
pod 'MPParallaxCollection'
